services:
  - type: web
    name: gem-admin-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3002
      - key: NODE_ENV
        value: production
